# Generated by Django 5.0.2 on 2024-02-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('runningTotal', models.BigIntegerField(default=0)),
                ('openingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('odLimit', models.BigIntegerField(default=0)),
            ],
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('interestRate', models.FloatField(default=0.0)),
            ],
            bases=('account.account',),
        ),
    ]
