# Generated by Django 5.0.2 on 2024-02-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('accountNo', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(max_length=50)),
                ('middleName', models.TextField(max_length=50, null=True)),
                ('lastName', models.TextField(max_length=50)),
                ('contactNo', models.IntegerField(default=0)),
                ('email', models.TextField(max_length=150)),
                ('password', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.customer')),
                ('companyType', models.TextField(choices=[('GOVERNMENT', 'Government'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NGO', 'Ngo')], default='PRIVATE')),
            ],
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.customer')),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], default='MALE')),
            ],
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.IntegerField(primary_key=True, serialize=False)),
                ('doorNo', models.TextField(max_length=5)),
                ('streetName', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
