# Generated by Django 5.0.2 on 2024-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
