# Generated by Django 5.0.2 on 2024-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('dot', models.DateField()),
            ],
        ),
    ]
