version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactionapi
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8001"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env



volumes:
  data:

networks:
  default:
    external:
      name: boanetwork